services:
  webshop-backend:
    build:
      context: ./webshop
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/webshop_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  database:
    image: postgres:latest
    container_name: backend-db
    restart: always
    environment:
      POSTGRES_DB: webshop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Mount the init folder
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "webshop_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s