name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  PROJECT_ID: dynamic-aurora-452119-a6
  GAR_LOCATION: us-central1
  REPO_NAME: docker-hub-webshop
  IMAGE_NAME: webshop-backend
  GKE_CLUSTER: autopilot-cluster-1-test
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: webshop-backend
  CONTAINER_NAME: webshop-backend-sha256

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: webshop

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Extract Version and Define Image Name
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          DATE=$(date +'%Y%m%d')
          IMAGE_NAME="webshop-backend-${VERSION}-${DATE}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        working-directory: webshop

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest .
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        working-directory: webshop

      - name: Configure Kubernetes Access
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Install GKE Auth Plugin Manually
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
          kubectl rollout status deployment/$DEPLOYMENT_NAME