name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: webshop

  create-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Version and Define Image Name
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          DATE=$(date +'%Y%m%d')
          IMAGE_NAME="ghcr.io/${{ github.repository }}/webshop-backend-${VERSION}-${DATE}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        working-directory: webshop

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
        working-directory: webshop

      - name: Push Docker Image to GitHub Container Registry
        run: docker push ${{ env.IMAGE_NAME }}
        working-directory: webshop