name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  PROJECT_ID: dynamic-aurora-452119-a6
  GAR_LOCATION: us-central1
  REPO_NAME: docker-hub-webshop
  IMAGE_NAME: webshop-backend
  GKE_CLUSTER: autopilot-cluster-1-test
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: webshop-backend
  CONTAINER_NAME: webshop-backend-sha256

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: webshop

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: dynamic-aurora-452119-a6
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Extract Version and Define Image Name
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          DATE=$(date +'%Y%m%d')
          IMAGE_NAME="webshop-backend-${VERSION}-${DATE}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        working-directory: webshop

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev
          gcloud --quiet auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest .
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        working-directory: webshop

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image $CONTAINER_NAME=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide